GoogleChrome/related-website-sets

- .github/workflows/fps-submissions-checks.yml
The Github Action should be modified to leave a comment on the PRs summarizing the success/failures on each check so that filers can more easily see the results of the Github action.
> change yaml to write comments on PRs

- FPS-Submission_Guidelines.md
- FpsCheck.py
- tests/fps_tests.py
As noted [here](https://github.com/WICG/first-party-sets/issues/149), certain web hosting plans have difficulty serving JSON files without the .json extension. To make submission easier for these maintainers, the .well-known requirement should be modified to require the JSON be served at /.well-known/first-party-set.json.
> Rename .well-known/first-party-set to include .json extension

- .github/workflows/fps-submissions-checks.yml
- FpsCheck.py
- check_sites.py
Currently, the workflow is set to "on: pull_request" which does not allow the workflow to have write permission to PRs made from forked repos. This issue is preventing comments from appearing on those PRs. Therefore, the workflow should be set to "on: pull_request_target" which will allow the action to have the needed write permissions, and other changes will be made to ensure that other aspects of the workflow remain safe during this process.
> Change workflow to run on PR request target

- FPS-Submission_Guidelines.md
- FpsCheck.py
- tests/fps_tests.py
After investigating the [issue relating to case-insensitivity](https://github.com/GoogleChrome/first-party-sets/issues/25), it was determined that this was not the source of a problem with the robots check as our code uses python's urllib library for requests, which implements a case-insensitive dictionary for request headers. 
However, it was determined that there were some issues with the current implementation of the robots check. In particular, we realized that the non-existence of a robots.txt does not prevent web-crawlers from indexing a page. Additionally, the exiting method of checking the 'X-Robots-Tag' would exclude values of the tag that ought to be valid. This PR makes corresponding changes in the code and the submission guide to fix these issues.
> policy and code changes for robots check

- FpsCheck.py
- FpsSet.py
- tests/fps_tests.py
The `com` exception added to `find_invalid_alias_eSLDs` mistakenly looked at the entire eTLD of the aliased domain, rather than the just the TLD, and checked for its presence in the ICANN list of country code top level domains. Sites that had country code TLDs but with eTLDs not on the list were thus inadvertently excluded from this exception. This meant that `example.ca` could have the alias `example.com` listed in its ccTLDs, but `example.co.uk` could not. This should be amended so that the check looks at just the TLDs when making the exceptions, creating the intended behavior in the check.
> change com exception in find_invalid_alias_eSLDs to look at TLD only

- FPS-Submission_Guidelines.md
Currently the FPS Submission guidelines incorrectly refer to variants having eTLDs on the PSL, when they should instead refer to the variants having TLDs on the ICANN list of country codes. This should be amended so that contributors can be certain what conditions their ccTLD variants must meet.
> Update wording for ccTLD guidelines

- first_party_sets.JSON
Reverts GoogleChrome/first-party-sets#36 because it is now failing the .well-known check for the associated domain [https://mystudentdashboard.com](https://mystudentdashboard.com/.well-known/first-party-set.json)
> Revert "Add FPS entry for Hapara.com"

- FpsCheck.py
- tests/fps_tests.py
Currently, `is_eTLD_Plus1` does not run as intended - it merely confirms that domain names it is passed contain a TLD in the PSL. The function should be changed to properly confirm that the domain does contain a TLD in the PSL, and that it is ONLY that domain plus one more level. For example, `primary.com` and `primary.co.uk` should both be accepted as "com" and "co.uk" are both listed in the PSL. However, `primary.example.com` should not be accepted as "example.com" is not listed in the PSL, therefore `primary.example.com` is two levels higher than a PSL listed domain.
> Account for multi-level domains in etld plus 1 check

- FpsCheck.py
- check_sites.py
- first_party_sets.JSON
- tests/fps_tests.py
Currently, the workflow does not run a check for a case where a pull request removes an entire set from the list. A check should therefore be added ensuring that the well-known page for the primary of a removed set serves an error 404. This will confirm that the set was intended to be removed from the list by the owner of the affected domain.
> Add check for subtracted sets

- FpsCheck.py
- FpsSet.py
- tests/fps_tests.py
Currently, if the well-known page of an FPS entry's primary contains a field that is not in the FPS entry itself, a NoneType Error will occur during the well-known check, and this will surface to the uploader when they attempt to make their PR, such as here as can be seen [here](https://github.com/GoogleChrome/first-party-sets/pull/67#issuecomment-1694200106). This error does not cause any technical issues with the FPS upload process, but it should be changed so that this case is properly caught and communicated to the uploader, allowing them to understand how their PR should be fixed in order to pass the checks and be merged.
> Fix well-known check to match fields of FPS entry with JSON file

- tests/fps_tests.py
Currently the argument passed to `Sys.path.append()` in `fps_tests.py` may make it difficult for developers to test locally. This PR will make it easier to for developers to run the unit tests on their local repo regardless of what they title their local directory.
> Fix path in unit tests to work more generally

- FpsCheck.py
This makes the error-constructing code a bit easier to read at a glance.
> Use fstrings instead of string concatenation for error strings

- README.md
Readme.md was missed by [the renaming PR](https://github.com/GoogleChrome/first-party-sets/pull/87), so its file references are now out of date. This PR updates those references to account for the FPS to RWS change.
> Change FPS references in Readme to RWS

- Getting-Started.md
Because of changes to the Submission Checks, running `check_sites.py` locally will cause a number of failures to appear related to older submissions that are not compliant with the changes. In order to make the testing process smoother for prospective submitters, this PR adds an explanation of a workaround that can be used to run the checks locally without having to see failures caused by older submissions.
> Add testing workaround in Getting Started Guide

- RWS-Submission_Guidelines.md
Pre Sept 2023 sites have `/.well-known/first-party-set.json`, not `/.well-known/related-website-set.json`.
For instance, see https://www.bild.de/.well-known/first-party-set.json
> Fixed docs to properly reflect pre-name-change file name

- tests/rws_tests.py
This adds a unit test proof that it's fine to include non-`"primary"` fields in the .well-known files for non-primary sites, and even include unsupported fields, without causing a validation error.
> Add unchecked fields to associated .well-known test

- Well-Known-Specification.md
In order to progress with registering the RWS well-known URI, we should specify what URI scheme we require, [as was suggested on the issue we filed](https://github.com/protocol-registries/well-known-uris/issues/40#issuecomment-1835374194).
> Add scheme requirement

- Getting-Started.md
- README.md
The content of the current "Getting Started" page should be replaced with a more detailed document. The information in the "Related Website Sets (RWS) Submission Quick-Start Guide and FAQs" is more up to date, and will hopefully better guide users through the initial process of creating and submitting their RWS, therefore reducing friction for both submitters and maintainers of this repository.
> Create Quick Start Guide

- Getting-Started.md
- check_sites.py
Currently, if users would like to locally test their changes to related_website_sets.JSON, they have to use [an awkward workaround](https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#step-4-testing-your-rws-locally). This change makes the workflow much simpler for users by adding an optional command line argument they can pass to check_sites.py when running it locally.
> Fix local testing workflow

- Getting-Started.md
We do not currently instruct uploaders to allow the RWS repo maintainers to make changes to their pull requests when they file it. [These permissions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) are needed when there is a merge conflict so that the RWS admin on review can resolve the conflicts and merge the PR when applicable.
> Add instruction for maintainer permissions

- RwsCheck.py
- tests/rws_tests.py
Fixes https://github.com/GoogleChrome/related-website-sets/issues/246 by explicitly disabling redirects on the `find_robots_txt` check. Adds asserts that this is the case in the tests.
This allows for the case where a service domain redirects to another domain that does not have the `X-Robots-Tag`.
This shouldn't change the behavior of non-redirecting which must either 4xx or 5xx when the home page is hit.
> Must have a homepage that redirects to a different domain or results in 4xx (client error) or 5xx (server error).
> Prevents redirects in the find_robots_txt check

- check_sites.py
JSONDecodeErrors were not properly handled in the `check_sites.py` script, meaning that the comment-bot wasn't surfacing the error to the submitters. This change fixes the formatting.
> Fix bug with concatenating JSONDecodeError

- related_website_sets.JSON
* Adds Related Website Set for stripe.com
* Well-known entries are in place for
* https://stripe.com/.well-known/related-website-set.json (primary)
* https://stripecdn.com/.well-known/related-website-set.json (service)
* https://stripe.network/.well-known/related-website-set.json (service)
* Root of both service domains redirect to primary home page
> Add Related Website Set for stripe.com

- .github/workflows/rws-submissions-checks.yml
This commit will cause the "RWS submission checks" to run daily at 9am EST. It utilizes the "schedule" event trigger and cron as described in https://docsgithub.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
> Trigger "RWS submission checks" action daily at 9am EST

- RwsCheck.py
- check_sites.py
- tests/rws_tests.py
While the robots check was modified in PR #28, that change did not properly modify the description of the function, and it left some extraneous bits of code. This Pr fixes resolves those issues.
> Remove robots references

- RwsCheck.py
- tests/rws_tests.py
There is currently a bug in how primaries are checked for as members of sets, causing the exclusivity check to improperly pass submissions that violate our guidelines. This PR fixes the exclusivity check, and adds additional testing to verify it.
> Fix check for primaries in subsets

- Getting-Started.md
- RWS-Submission_Guidelines.md
This change introduces information on how "Stale PRs" (failing pull requests that have not been updated in over 30 days) will be handled by reviewers.
> Add stale PR direction

- .github/workflows/main.yml
- .github/workflows/pr.yml
Let's update the GitHub comment with an alert if system files (non-RWS-JSON) changes are in the PR.
This also fixes an issue with the name of the PR build that prevents checks from looking as though they passed.
Here's an example of the comment:
> Alert in comment on system file changes

- .github/workflows/pr.yml
We want the action to initiate from the base commit on the main repo, but want to evaluate the code on the merge commit.
> Fix checkout target

- check_sites.py
- tests/rws_tests.py
I think this will give more context (like line numbers) when reporting formatting differences, that should make it easier to know where the problems are.
> Use unified diff format when reporting formatting issues

- .github/workflows/code.yml
- .github/workflows/json.yml
- .github/workflows/main.yml
We need two jobs:
1. a job that can only be triggered by a trusted source that runs new python code
2. a job that can be triggered by any fork, but just evaluates the new JSON and can make comments
> Split pull request jobs

- RWS-Submission_Guidelines.md
- SCHEMA.json
- tests/rws_tests.py
This addresses some of the feedback in https://github.com/GoogleChrome/related-website-sets/issues/506. Namely:
* Fixes the expected location of the "contact" property
* Disallows unexpected properties in the top-level object
* Disallows unexpected properties in each set entry
* Requires that each entry's associated sites are unique
* Requires that each entry's service sites are unique
* Requires that each entry has at least one of the "associatedSites", "serviceSites", or "ccTLDs" keys
> Fix schema, make it stricter, add tests

- .github/workflows/json.yml
Let's use https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary too, then maybe we can remove the comment in the future.
> Add JSON Actions Summary

- related_website_sets.JSON
Reverts GoogleChrome/related-website-sets#710
Instead of merging test sets, users should be [using flags](https://developers.google.com/privacy-sandbox/blog/first-party-sets-testing-instructions#how_to_test_locally) for pure testing purposes. 
cc @dimitarandonov
> Revert "gfk sensic domains "

- tests/rws_tests.py
This ensures that validation fails for the right reason, i.e. that we're testing the thing that we intend to be testing.
> Be more specific about expected schema validation failures

- check_sites.py
- tests/rws_tests.py
Currently, if `parse_rws_json` is called on a JSON file that is readable but not properly formatted, we only print the formatting errors and don't run any of the other technical checks. This change makes it so that as long JSON file is readable, we still attempt to run all other technical checks so that submitters can see if their submission is invalid in other ways aside from their formatting.
> Allow other errors to be listed when there is a formatting error

- .github/workflows/json.yml
The existing code used character classes within a string literal, so it should have double-escaped them, e.g. `"Not\\s+a..."`. JS provides a more concise syntax for regex literals which doesn't require double-escaping, so we'll use that instead.
> Fix regex-escaping bug

- .github/workflows/json.yml
Apparently `bodyText` doesn't exist (per https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request), despite https://docs.github.com/en/graphql/reference/objects#pullrequest saying it does.
> Use `pull_request.body` instead of `pull_request.bodyText`
