- first_party_sets.JSON
This is a retry of #11 with the .json versions of files under .well-known
> Small set with two associated domains

- first_party_sets.JSON
All checks for the associated domains should be passing now :)
> Add FPS entry for Hapara.com

- SCHEMA.json
- first_party_sets.JSON
first_party_set update with my primary and associate url
> first_party_set updated

- FpsCheck.py
- tests/fps_tests.py
This mainly uses different python APIs and takes advantage of the changes to the FpsSet class in 9309ad4.
It does change some error messages to be more accurate, and fixes a bug that could have caused the same error message to be reported multiple times.
> Refactor some loops to be more idiomatic

- related_website_sets.JSON
Add relations for Wildix infrastructure domains.
> Add Wildix RWS

- related_website_sets.JSON
We have added our Related Websites for Times Internet
> Added RWS for Times Internet Ltd

- related_website_sets.JSON
> Add RWS KG Media

- related_website_sets.JSON
> Added section for https://hearty.me

- related_website_sets.JSON
> Added section for https://nien.com

- Well-Known-Specification.md
- related_website_sets.JSON
Updating RWS to reflect set size increase in Chrome M117 (see https://developers.google.com/privacy-sandbox/blog/related-website-sets?hl=en)
> Update Related Website Set for Wirtualna Polska Media

- related_website_sets.JSON
[Startup Island Taiwan](https://startupislandtaiwan.com)
> Added section for https://startupislandtaiwan.com

- RWS-Submission_Guidelines.md
This performs the same fix as #284, just saves them the time of having to fill out the CLA.
> Fix formatting in submission guidelines

- related_website_sets.JSON
> Submit RWS for Zalo

- related_website_sets.JSON
Reverts GoogleChrome/related-website-sets#371
Reason: https://github.com/GoogleChrome/related-website-sets/pull/371#issuecomment-2103432161
> Revert "Update related_website_sets.JSON"

- related_website_sets.JSON
> add new site

- related_website_sets.JSON
> Adding Naukri.com Related Website Set

- related_website_sets.JSON
Add TheJournal Media Related Websites Set record.
> Add TheJournalMedia RWS record

- related_website_sets.JSON
Add AdShield related RWS record.
> Add AdShield RWS record

- related_website_sets.JSON
Add Interia related RWS record.
> Add Interia RWS record

- check_sites.py
- tests/rws_tests.py
Formatting is really weird unless we make this a codeblock https://github.com/GoogleChrome/related-website-sets/pull/672#issuecomment-2528545897
> Fix formatting GitHub Comment

- .github/workflows/pr.yml
Let's cut this for now and restore it only when issues are resolved
> Remove write permission GitHub token from repo

- .github/workflows/json.yml
It's not that helpful and could cause issues.
> Don't list files in commit message

- .github/workflows/code.yml
Let's check all of the JSON but not force errors if it doesn't pass. Test failures still cause job failure.
> Improve "code" Action

- related_website_sets.JSON
I ran `check_sites.py -p https://undertale.wiki` already, but I'm not sure if that will be enough for CI to pass.
> undertale.wiki and deltarune.wiki
